repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
        args: [ --branch, main ]
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-json
      # - id: check-yaml # does not play well with Helm
      # - id: detect-aws-credentials
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
      # - id: helmlint  # Does not work with Version: [[ .Version ]] in Chart.yaml
