apiVersion: v2
name: cluster-azure
description: A helm chart for creating Cluster API clusters with the Azure provider (CAPZ).
version: 8.0.0
home: https://github.com/giantswarm/cluster-azure
icon: https://s.giantswarm.io/app-icons/azure/1/light.svg
sources:
- https://github.com/giantswarm/cluster-azure
maintainers:
- name: Team Phoenix
  email: team-phoenix@giantswarm.io
keywords:
- capz
- azure
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: phoenix
restrictions:
  compatibleProviders:
  - azure
dependencies:
- repository: https://giantswarm.github.io/cluster-test-catalog
  name: cluster
  version: 7.0.1-dev.migrate-app--elmreleases.2026-08-04.14-15-21.h66e00d7
