# Cluster name. Defaults to chart release name
clusterName: ""
# Cluster description used in metadata.
clusterDescription: "test"
# Organization in which to create the cluster.
organization: ""
kubernetesVersion: 1.24.8

azure:
  location: "westeurope"
  # This value must be updated to the right value for the cluster to be installed
  subscriptionId: PLACEHOLDER
  azureClusterIdentity:
    name: "cluster-identity"
    namespace: "org-giantswarm"

network:
  serviceCIDR: 172.31.0.0/16
  podCIDR: "192.168.0.0/16"
  hostCIDR: "10.0.0.0/8"

controlPlane:
  instanceType: Standard_D4s_v3
  # Number of replicas in control plane. Should be an odd number.
  replicas: 1
  rootVolumeSizeGB: 50
  etcdVolumeSizeGB: 10

machinePools:
  - name: def00
    location: "westeurope"
    instanceType: Standard_D2s_v3
    minSize: 3
    maxSize: 3
    rootVolumeSizeGB: 50
    customNodeLabels:
      - label=default
    customNodeTaints: []
    # - key: ""
    #   value: ""
    #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.

# Only required until we have AZWI for CAPZ
attachCapzControllerIdentity: false

# TODO: This is temporary so we can deploy clusters without dedicated UA Identity until the operator for WC clusters are ready
# https://github.com/giantswarm/giantswarm/issues/25039
enablePerClusterIdentity: false

# TODO: This is temporary to control the use of the has in naming of machinepool resources
enableMachinePoolHashing: false

sshSSOPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnfhWCBrplizz7XzX1Sc+I57TvCe+EEARTeYBuqWa3BRNVysSdPdbxHHJ6qzVY66snO4wq4yokno0yBdA7hAV73Y38/yZEzdKux+UyRwrnoerOdOw/590U6Pkm1mB9YhUQ4XrS5j67ZNUc/LeSQ+aWf65HATcLUccfIIVNt7OOEl+VGvg9Pvoukg+A/mSoYdBQssGNbzB+8niK5ohIsKMxS0aqaLlEZMtXxZuD8YDvIRO2m8n+djQ6wqi4HTVcBKRREa5blVu3Ug42O4XDvcdHxqHyPCUSU7ho/PJDR1B45gub+hKt/O4EdtzVZE4Z7hGQEfXUd5C0mbg+V5gcxLtt"

oidc:
  issuerUrl: ""
  caPem: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""
