# Cluster name. Defaults to chart release name
clusterName: ""
# Cluster description used in metadata.
clusterDescription: "test"
# Organization in which to create the cluster.
organization: ""
kubernetesVersion: 1.22.7
releaseVersion: 20.0.0-alpha1

azure:
  location: "westeurope"

network:
  bastionSubnet: "10.2.0.0/16"
  controlPlaneSubnet: "10.0.0.0/16"
  # cidr range for the VPC
  vnetCIDR: 10.0.0.0/8
  serviceCIDR: 172.31.0.0/16
  podCIDR: "192.168.0.0/16"
  podNodeCidr: 24

bastion:
  vmSize: Standard_D2_v3
  replicas: 1

controlPlane:
  vmSize: Standard_D4s_v3
  # Number of replicas in control plane. Should be an odd number.
  replicas: 1
  rootVolumeSizeGB: 120
  etcdVolumeSizeGB: 100

machinePools:
  # Name of node pool.
  - name: def00
    availabilityZones:
    instanceType: m5.xlarge
    # Number of replicas in node pool.
    minSize: 3
    maxSize: 3
    rootVolumeSizeGB: 300
    customNodeLabels:
      - label=default

# TODO Is this the right place in the schema ? 
vmIdentity:
  type: null
  userAssignedIdentitiesIds: []

sshSSOPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io"

# Used by `cluster-shared` library chart
includeClusterResourceSet: true
kubectlImage:
  registry: quay.io
  name: giantswarm/kubectl
  tag: 1.23.5
