# Cluster name. Defaults to chart release name
clusterName: ""
# Cluster description used in metadata.
clusterDescription: "test"
# Organization in which to create the cluster.
organization: ""
kubernetesVersion: 1.24.8

azure:
  location: "westeurope"
  # This value must be updated to the right value for the cluster to be installed
  subscriptionId: PLACEHOLDER

network:
  serviceCIDR: 172.31.0.0/16
  podCIDR: "192.168.0.0/16"

controlPlane:
  instanceType: Standard_D4s_v3
  # Number of replicas in control plane. Should be an odd number.
  replicas: 1
  rootVolumeSizeGB: 50
  etcdVolumeSizeGB: 10

machinePools:
  - name: def00
    location: "westeurope"
    instanceType: Standard_D2s_v3
    minSize: 3
    maxSize: 3
    rootVolumeSizeGB: 50
    customNodeLabels:
      - label=default
    customNodeTaints: []
    # - key: ""
    #   value: ""
    #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.

# define if the cluster being installed is a MC or a WC (default)
managementCluster: false

# TODO: This is temporary so we can deploy clusters without dedicated UA Identity until the operator for WC clusters are ready
# https://github.com/giantswarm/giantswarm/issues/25039
enablePerClusterIdentity: false

sshSSOPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io"

oidc:
  issuerUrl: ""
  caPem: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""
