# Cluster name. Defaults to chart release name
clusterName: ""
# Cluster description used in metadata.
clusterDescription: "test"
# Organization in which to create the cluster.
organization: ""
kubernetesVersion: 1.24.8

azure:
  location: "westeurope"
  # This value must be updated to the right value for the cluster to be installed
  subscriptionId: PLACEHOLDER
  azureClusterIdentity:
    name: "cluster-identity"
    namespace: "org-giantswarm"

network:
  serviceCIDR: 172.31.0.0/16
  podCIDR: "192.168.0.0/16"
  hostCIDR: "10.0.0.0/8"

controlPlane:
  instanceType: Standard_D4s_v3
  # Number of replicas in control plane. Should be an odd number.
  replicas: 1
  rootVolumeSizeGB: 50
  etcdVolumeSizeGB: 10

defaults:
  softEvictionThresholds: memory.available<500Mi,nodefs.available<15%,nodefs.inodesFree<5%,imagefs.available<15%,pid.available<30%
  softEvictionGracePeriod: memory.available=30s,nodefs.available=2m,nodefs.inodesFree=1m,imagefs.available=2m,pid.available=1m
  hardEvictionThresholds: memory.available<200Mi,nodefs.available<10%,nodefs.inodesFree<3%,imagefs.available<10%,pid.available<20%
  evictionMinimumReclaim: imagefs.available=5%,memory.available=100Mi,nodefs.available=5%
  identity:
    #Only SystemAssigned or UserAssigned supported
    type: SystemAssigned
    #Not used yet https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2965/files
    scope: </subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP_NAME}>
    #Not used yet https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2965/files
    roleDefinitionID: </subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c>
    #Pass list of UA Identities to attach to nodes, if empty defaults -cp ,-nodes, -capz are used
    userAssignedIdentities: []

machinePools:
  - name: def00
    location: "westeurope"
    instanceType: Standard_D2s_v3
    minSize: 3
    maxSize: 3
    rootVolumeSizeGB: 50
    customNodeLabels:
      - label=default
    customNodeTaints: []
    # - key: ""
    #   value: ""
    #   effect: "" # Valid effects are NoSchedule, PreferNoSchedule and NoExecute.

# Categorize this cluster as Management Cluster or Workload Cluster
managementCluster: false

sshSSOPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnfhWCBrplizz7XzX1Sc+I57TvCe+EEARTeYBuqWa3BRNVysSdPdbxHHJ6qzVY66snO4wq4yokno0yBdA7hAV73Y38/yZEzdKux+UyRwrnoerOdOw/590U6Pkm1mB9YhUQ4XrS5j67ZNUc/LeSQ+aWf65HATcLUccfIIVNt7OOEl+VGvg9Pvoukg+A/mSoYdBQssGNbzB+8niK5ohIsKMxS0aqaLlEZMtXxZuD8YDvIRO2m8n+djQ6wqi4HTVcBKRREa5blVu3Ug42O4XDvcdHxqHyPCUSU7ho/PJDR1B45gub+hKt/O4EdtzVZE4Z7hGQEfXUd5C0mbg+V5gcxLtt"

oidc:
  issuerUrl: ""
  caPem: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""
