baseDomain: azuretest.gigantic.io
connectivity:
  bastion:
    enabled: true
    instanceType: Standard_D2s_v5
  network:
    controlPlane:
      cidr: 10.0.0.0/20
    hostCidr: 10.0.0.0/16
    mode: public
    podCidr: 192.168.0.0/16
    serviceCidr: 172.31.0.0/16
    workers:
      cidr: 10.0.16.0/20
  sshSSOPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io
controlPlane:
  etcdVolumeSizeGB: 10
  instanceType: Standard_D4s_v3
  oidc:
    caPem: ""
    clientId: ""
    groupsClaim: ""
    issuerUrl: ""
    usernameClaim: ""
  replicas: 3
  rootVolumeSizeGB: 50
internal:
  defaults:
    evictionMinimumReclaim: imagefs.available=5%,memory.available=100Mi,nodefs.available=5%
    hardEvictionThresholds: memory.available<200Mi,nodefs.available<10%,nodefs.inodesFree<3%,imagefs.available<10%,pid.available<20%
    softEvictionGracePeriod: memory.available=30s,nodefs.available=2m,nodefs.inodesFree=1m,imagefs.available=2m,pid.available=1m
    softEvictionThresholds: memory.available<500Mi,nodefs.available<15%,nodefs.inodesFree<5%,imagefs.available<15%,pid.available<30%
  identity:
    attachCapzControllerIdentity: false
    enablePerClusterIdentity: false
  image:
    gallery: gsCapzFlatcar-41c2d140-ac44-4d8b-b7e1-7b2f1ddbe4d0
    name: '{{ printf "capi-flatcar-stable-%s-gen2" .Values.internal.kubernetesVersion }}'
    version: latest
  kubernetesVersion: 1.24.11
metadata:
  servicePriority: highest
nodePools:
  - customNodeLabels: []
    customNodeTaints: []
    disableHealthCheck: false
    instanceType: Standard_D2s_v3
    name: md00
    replicas: 3
    rootVolumeSizeGB: 50
providerSpecific:
  azureClusterIdentity:
    name: cluster-identity
    namespace: org-giantswarm
  location: westeurope
  subscriptionId: PLACEHOLDER
