{{- /* Azure-specific cert-manager Helm values */}}
{{- /* https://github.com/giantswarm/cert-manager-app/blob/main/helm/cert-manager/values.yaml */}}
{{- define "azureCertManagerHelmValues" }}
{{- if (include "useCertManagerDnsChallenges" $ | eq "true") }}
{{- /* Get cert-manager version. */}}
{{- $version := "N/A" }}
{{- if .Values.providerIntegration.useReleases }}
{{- $_ := set $ "appName" "cert-manager" }}
{{- $version = include "cluster.app.version" $ | trim }}
{{- end }}
{{- /* Check cert-manager version. Since v4.0.0, upstream properties need to be under the `cert-manager` key. */}}
{{- if or (eq $version "N/A") (semverCompare ">=4.0.0" $version) }}
cert-manager:
  dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53
{{- else }}
dns01RecursiveNameservers: 8.8.8.8:53,1.1.1.1:53
{{- end }}

{{- /* Top-level custom properties (independent of upstream). */}}
giantSwarmClusterIssuer:
  acme:
    dns01:
      azureDNS:
        enabled: true
        identityClientID: {{ .Values.global.providerSpecific.identityClientID }}
        subscriptionID: {{ .Values.global.providerSpecific.subscriptionId }}
        resourceGroupName: {{ include "resource.default.name" $ }}
        zoneName: {{ printf "%s.%s" (include "resource.default.name" $) .Values.global.connectivity.baseDomain | quote }}
    http01:
       enabled: false
{{- end }}
{{- end }}
