{{- define "csi-driver-helm-release" }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-azuredisk-csi-driver
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- if .Values.metadata.servicePriority }}
    giantswarm.io/service-priority: {{ .Values.metadata.servicePriority }}
    {{- end }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: azuredisk-csi-driver
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: azuredisk-csi-driver-app
      version: 1.26.2-gs1 # TODO: Should we move this to the values / helper to make sure all versions are configured close to each other to make things easier for updates ? 
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/azure-cloud-controller-manager-app/blob/main/helm/azure-cloud-controller-manager-app/values.yaml
  values:
    {{- include "values.common" . | nindent 4 }}
    controller:
      disableAvailabilitySetNodes: false
    linux:
      azure_credential_file: /etc/kubernetes/azure.json
{{- end -}}
