apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-azure-cloud-controller-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- if .Values.metadata.servicePriority }}
    giantswarm.io/service-priority: {{ .Values.metadata.servicePriority }}
    {{- end }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: azure-cloud-controller-manager
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: azure-cloud-controller-manager-app
      version: 1.24.18-gs1-d6fac690d57601c2df6ed7883cd2adf5e0a355cb # TODO: Should we move this to the values / helper to make sure all versions are configured close to each other to make things easier for updates ? 
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default-test
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 2m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/azure-cloud-controller-manager-app/blob/main/helm/azure-cloud-controller-manager-app/values.yaml
  values:
    cluster:
      calico:
        CIDR: {{ .Values.connectivity.network.podCidr | quote }}
    controller:
      azureCredentialFile: "/etc/kubernetes/azure.json"
      controlPlaneNodeSelector:
        "kubernetes.io/role": null
        "node-role.kubernetes.io/control-plane": '""'
      kubeconfigFromHost: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-azure-cloud-node-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- if .Values.metadata.servicePriority }}
    giantswarm.io/service-priority: {{ .Values.metadata.servicePriority }}
    {{- end }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: azure-cloud-node-manager
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: azure-cloud-node-manager-app
      version: 1.24.18-gs1-a9651b3c53d47cdf48109b6967e2bec0cd68784a # TODO: Should we move this to the values / helper to make sure all versions are configured close to each other to make things easier for updates ? 
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default-test
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 2m
  install:
    remediation:
      retries: 30
