---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-vertical-pod-autoscaler-crd
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: vertical-pod-autoscaler-crd
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: vertical-pod-autoscaler-crd
      # used by renovate
      # repo: giantswarm/vertical-pod-autoscaler-crd
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 1m
  install:
    remediation:
      retries: 30
  values:
    global:
      podSecurityStandards:
        enforced: {{ .Values.global.podSecurityStandards.enforced }}

