managementCluster: MCCLUSTER
provider: capz

providerSpecific:
  subscriptionId: 12345678-abcd-1234-abcd-1234567abcde

global:
  metadata:
    organization: test
    servicePriority: lowest
    labels:
      test.io/testing: test-label
  connectivity:
    baseDomain: azuretest.gigantic.io
