managementCluster: MCCLUSTER
provider: capz

global:
  metadata:
    name: test-wc
    organization: test
    servicePriority: lowest
    labels:
      test.io/testing: test-label
  nodePools:
    def00:
      instanceType: Standard_D4s_v5
      replicas: 2
      rootVolumeSizeGB: 50
      machineHealthCheck:
        enabled: true
        maxUnhealthy: 40%
        nodeStartupTimeout: 10m
        unhealthyNotReadyTimeout: 300s
        unhealthyUnknownTimeout: 300s
  conn ectivity:
    baseDomain: azuretest.gigantic.io
  providerSpecific:
    subscriptionId: 12345678-abcd-1234-abcd-1234567abcde
  managementCluster: MCCLUSTER
