managementCluster: MCCLUSTER
provider: capz

global:
  metadata:
    name: test-wc
    organization: test
    servicePriority: lowest
  nodePools:
    md0:
      instanceType: Standard_D4s_v5
      replicas: 2
      rootVolumeSizeGB: 50
    labels:
      test.io/testing: test-label
  connectivity:
    baseDomain: azuretest.gigantic.io
  providerSpecific:
    subscriptionId: 12345678-abcd-1234-abcd-1234567abcde
  managementCluster: MCCLUSTER
