metadata:
  name: test-wc-restricted
  organization: test
  servicePriority: lowest

connectivity:
  allowedCIDRs:
    - "1.1.1.1"
    - "8.8.8.8"

providerSpecific:
  location: "westeurope"
  subscriptionId: "PLACEHOLDER_SUBSCRIPTION_ID"

internal:
  identity:
    type: "SystemAssigned"
    systemAssignedScope: "Subscription"
