global:
  managementCluster: test-mc
  metadata:
    name: test-wc-byon
    organization: giantswarm
    preventDeletion: false
    servicePriority: lowest
  connectivity:
    network:
      mode: byon
      name: byon-vnet
      resourceGroup: byon-rg
      hostCidr: 10.224.17.0/24
      controlPlane:
        subnetName: controlplane-subnet
        cidr: 10.224.17.128/26
        routeName: workers-rt
        securityGroupName: controlplane-nsg
      workers:
        subnetName: workers-subnet
        cidr: 10.224.17.0/25
        routeName: workers-rt
        securityGroupName: workers-nsg
  providerSpecific:
    location: "westeurope"
    subscriptionId: 7128b61f-826e-4078-bdc6-f3ff51de12fd
  release:
    version: 35.0.1

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
