global:
  managementCluster: test-mc
  metadata:
    name: test-mc
    organization: test
    servicePriority: lowest
  connectivity:
    network:
      controlPlane:
        cidr: 10.0.16.128/26
        subnetName: cluster-cp-subnet
      hostCidr: 10.0.16.0/24
      mode: public
      pods:
        cidrBlocks:
        - 192.168.0.0/16
      services:
        cidrBlocks:
        - 172.31.0.0/16
      workers:
        cidr: 10.0.16.0/25
        subnetName: cluster-node-subnet
        natGatewayName: cluster-node-natgateway
  controlPlane:
    oidc:
      clientId: dex-k8s-authenticator
      issuerUrl: https://dex.cluster.azuretest.gigantic.io
      groupsClaim: groups
      usernameClaim: email
  nodePools:
    def00:
      instanceType: Standard_D4s_v5
      replicas: 4
      rootVolumeSizeGB: 50
  providerSpecific:
    location: "westeurope"
    subscriptionId: 12345678-abcd-1234-abcd-1234567abcde

internal:
  network:
    vnet:
      resourceGroup: vnet-test-rg
      name: vnet-test
