global:
  managementCluster: test-mc
  metadata:
    name: test-wc
    organization: giantswarm
    preventDeletion: false
    servicePriority: lowest
    labels:
      cluster.giantswarm.io/test: value1
  connectivity:
    allowedCIDRs:
    - 192.168.1.0/24
    network:
      controlPlane:
        cidr: 10.0.16.128/26
        privateEndpoints:
        - name: testing-pe
          privateLinkServiceConnections:
          - name: testing-pl
            privateLinkServiceID: /subscriptions/12345678-9abc-def0-1234-567890abcdef/resourceGroups/rg1/providers/Microsoft.Network/privateLinkServices/privatelink1
      hostCidr: 10.0.16.0/24
      mode: public
      peerings:
      - remoteVnetName: peer
        resourceGroup: peer-rg
      pods:
        cidrBlocks:
        - 192.168.0.0/16
      services:
        cidrBlocks:
        - 172.31.0.0/16
      workers:
        cidr: 10.0.16.0/25
        privateEndpoints:
        - name: testing-pe
          privateLinkServiceConnections:
          - name: testing-pl
            privateLinkServiceID: /subscriptions/12345678-9abc-def0-1234-567890abcdef/resourceGroups/rg1/providers/Microsoft.Network/privateLinkServices/privatelink1
  controlPlane:
    oidc:
      clientId: dex-k8s-authenticator
      issuerUrl: https://dex.cluster.azuretest.gigantic.io
      groupsClaim: groups
      usernameClaim: email
  nodePools:
    def00:
      instanceType: Standard_D4s_v5
      replicas: 4
      rootVolumeSizeGB: 50
  providerSpecific:
    failureDomains:
    - "1"
    - "3"
    location: "westeurope"
    network:
      peerings:
      - remoteVnetName: peer
        resourceGroup: peer-rg
    subscriptionId: 12345678-abcd-1234-abcd-1234567abcde
  release:
    version: v25.0.0

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true

internal:
  kubernetesVersion: 1.25.10
