global:
  metadata:
    name: test-wc-restricted
    organization: test
    preventDeletion: false
    servicePriority: lowest
  connectivity:
    allowedCIDRs:
      - "1.1.1.1"
      - "8.8.8.8"
  providerSpecific:
    identity:
      systemAssignedScope: "Subscription"
    location: "westeurope"
    subscriptionId: 12345678-abcd-1234-abcd-1234567abcde
  release:
    version: v25.0.0

cluster:
   internal:
     ephemeralConfiguration:
       offlineTesting:
         renderWithoutReleaseResource: true
