global:
  metadata:
    name: test-wc-restricted
    organization: test
    servicePriority: lowest
  connectivity:
    allowedCIDRs:
      - "1.1.1.1"
      - "8.8.8.8"

providerSpecific:
  location: "westeurope"
  subscriptionId: 12345678-abcd-1234-abcd-1234567abcde

internal:
  identity:
    type: "SystemAssigned"
    systemAssignedScope: "Subscription"
