metadata:
  name: test-wc
  organization: test
  servicePriority: lowest
  clusterLabels:
    cluster.giantswarm.io/test: value1

providerSpecific:
  location: "westeurope"
  subscriptionId: "PLACEHOLDER_SUBSCRIPTION_ID"

connectivity:
  network:
    controlPlane:
      cidr: 10.0.16.128/26
    hostCidr: 10.0.16.0/24
    mode: public
    podCidr: 192.168.0.0/16
    serviceCidr: 172.31.0.0/16
    workers:
      cidr: 10.0.16.0/25
nodePools:
  - name: md00
    instanceType: Standard_D4s_v5
    replicas: 4
    rootVolumeSizeGB: 50
controlPlane:
  oidc:
    clientId: dex-k8s-authenticator
    issuerUrl: https://dex.cluster.azuretest.gigantic.io
    groupsClaim: groups
    usernameClaim: email
