{{/* Azure-specific cilium Helm values*/}}
{{/* https://github.com/giantswarm/cert-manager-app/blob/main/helm/cert-manager/values.yaml*/}}
{{- define "azureCertManagerHelmValues" }}
{{- if $.Values.global.providerSpecific}}
# cert-manager's DNS01 solver by default tries to reach authoritative nameservers directly, using
# their public IPs. Since those are not reachable from private clusters, we instead rely on the
# recursive nameserver
#
# For public clusters, this setting should have no effect, as they can use the HTTP01 solver.

# check extra config for private WC parameters
# note that user config has higher priority and extra config can be overwritten by userConfig
dns01RecursiveNameserversOnly: true
ciliumNetworkPolicy:
  enabled: true
{{- if .Values.global.connectivity.network.mode == "private" }}
dns01RecursiveNameservers: "8.8.8.8:53,1.1.1.1:53"
giantSwarmClusterIssuer:
  acme:
  http01:
     enabled: false
  dns01:
    azureDNS:
    enabled: true
    zoneName: "{{ .Values.baseDomain }}"
    resourceGroupName: {{ include "resource.default.name" $ }}
    subscriptionID: {{ .Values.global.providerSpecific.subscriptionID }}
    identityClientID: {{ .Values.global.providerSpecific.identityClientID }}
{{- end }}
{{- end }}
{{- end }}
