{{/* Azure-specific cilium Helm values*/}}
{{/* https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml*/}}
{{- define "azureCiliumHelmValues" }}
ipam:
  mode: kubernetes
k8sServiceHost: apiserver.{{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}
k8sServicePort: '6443'
kubeProxyReplacement: strict
hubble:
  relay:
  enabled: true
defaultPolicies:
  remove: true
  enabled: false
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
global:
  podSecurityStandards:
  enforced: {{ .Values.global.podSecurityStandards.enforced }}
{{- end }}
