{{/* Azure-specific external-dns Helm values*/}}
{{/* https://github.com/giantswarm/external-dns-app/blob/main/helm/external-dns-app/values.yaml*/}}
{{- define "azureExternalDnsHelmValues" }}
provider: azure
clusterID: {{ include "resource.default.name" $ }}
domainFilters:
  - "{{ .Values.global.connectivity.baseDomain }}"
txtOwnerId: giantswarm-io-external-dns
txtPrefix: {{ include "resource.default.name" $ }}

{{/*
  Setting up Azure Managed Identity
  We do this ourselves to avoid having external-dns depend on a webhook.
  It also requires data from a Secret that is deployed by the WorkloadIdentity resource
  in the external-dns-crossplane-resources HelmRelease.
*/}}
env:
  - name: AZURE_FEDERATED_TOKEN_FILE
    value: /var/run/secrets/azure/tokens/azure-identity
  - name: AZURE_AUTHORITY_HOST
    value: https://login.microsoftonline.com/
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        key: clientID
        name: external-dns
  - name: AZURE_TENANT_ID
    valueFrom:
      secretKeyRef:
        key: tenantID
        name: external-dns
extraVolumes:
  - name: azure-identity-token
    projected:
      defaultMode: 420
      sources:
        - serviceAccountToken:
            audience: api://AzureADTokenExchange
            expirationSeconds: 3600
            path: azure-identity
extraVolumeMounts:
  - mountPath: /var/run/secrets/azure/tokens
    name: azure-identity-token
    readOnly: true
{{- end }}
