{{/* Azure-specific external-dns-private Helm values*/}}
{{/* https://github.com/giantswarm/external-dns-app/blob/main/helm/external-dns-app/values.yaml*/}}
{{- define "azureExternalDnsPrivateHelmValues" }}
provider: azure-private-dns
clusterID: {{ include "resource.default.name" $ }}
crd:
  install: false
domainFilters:
  - "{{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}"
txtOwnerId: giantswarm-io-external-dns
txtPrefix: {{ include "resource.default.name" $ }}
extraVolumes:
  - name: azure-config-file
    hostPath:
      path: /etc/kubernetes
extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true
ciliumNetworkPolicy:
  enabled: true
{{- if (.Values.global.connectivity.proxy).enabled }}
env:
  - name: NO_PROXY
    value: {{ .Values.global.connectivity.proxy.noProxy | quote }}
  - name: HTTP_PROXY
    value: {{ .Values.global.connectivity.proxy.httpProxy | quote }}
  - name: HTTPS_PROXY
    value: {{ .Values.global.connectivity.proxy.httpsProxy | quote }}
{{- end }}
{{- end }}
