{{/* Azure-specific security-bundle Helm values*/}}
{{/* https://github.com/giantswarm/security-bundle/blob/main/helm/security-bundle/values.yaml*/}}
{{- define "azureSecurityBundleHelmValues" }}
userConfig:
  kyverno:
    configMap:
      values:
        kyverno:
          admissionController:
            tolerations:
            - key: "node.cluster.x-k8s.io/uninitialized"
              operator: "Exists"
              effect: "NoSchedule"
{{- end }}
