{{/* Default Helm values for the app */}}
{{/* See schema for the appropriate app version here https://github.com/giantswarm/azure-cloud-node-manager-app/blob/master/helm/aws-cloud-node-manager-app/values.schema.json */}}
{{- define "defaultAzureCloudNodeManagerHelmValues" }}
verticalPodAutoscaler:
  enabled: {{ .Values.internal.enableVpaResources }}
global:
  podSecurityStandards:
    enforced: {{ .Values.global.podSecurityStandards.enforced }}
# kyverno installs PolicyException CRs for core components on CAPI clusters
deployPolicyExceptions: false
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-azure-cloud-node-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- if .Values.global.metadata.servicePriority }}
    giantswarm.io/service-priority: {{ .Values.global.metadata.servicePriority }}
    {{- end }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: azure-cloud-node-manager
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: azure-cloud-node-manager-app
      # used by renovate
      # repo: giantswarm/azure-cloud-node-manager-app
      version: 1.24.18-gs6
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-vertical-pod-autoscaler-crd
      namespace: {{ $.Release.Namespace }}
  interval: 2m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/giantswarm/azure-cloud-controller-manager-app/blob/main/helm/azure-cloud-controller-manager-app/values.yaml
  values:
  {{- $azureCloudNodeManagerHelmValues := (include "defaultAzureCloudNodeManagerHelmValues" .) | fromYaml -}}
  {{- $customAzureCloudNodeManagerHelmValues := $.Values.global.apps.azureCloudNodeManager.values -}}
  {{- if $customAzureCloudNodeManagerHelmValues }}
  {{- $azureCloudNodeManagerHelmValues = merge (deepCopy $customAzureCloudNodeManagerHelmValues) $azureCloudNodeManagerHelmValues -}}
  {{- end }}
  {{- if $azureCloudNodeManagerHelmValues }}
  values: {{- $azureCloudNodeManagerHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.azureCloudNodeManager.extraConfigs }}
  valuesFrom:
    {{- range $config := $.Values.global.apps.azureCloudNodeManager.extraConfigs }}
    - kind: {{ $config.kind }}
      name: {{ $config.name }}
      valuesKey: values
      optional: {{ $config.optional | default false  }}
    {{- end }}
  {{- end }}
