{{/* Azure-specific external-dns app for private clusters */}}
{{- if eq .Values.global.connectivity.network.mode "private" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}-external-dns-private-user-values
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  values: |
    provider: azure-private-dns
    clusterID: {{ include "resource.default.name" $ }}
    crd:
      install: false
    domainFilters:
      - "{{ include "resource.default.name" $ }}.{{ .Values.global.connectivity.baseDomain }}"
    txtOwnerId: giantswarm-io-external-dns
    txtPrefix: {{ include "resource.default.name" $ }}
    sources:
      - service
    extraVolumes:
      - name: azure-config-file
        hostPath:
          path: /etc/kubernetes
    extraVolumeMounts:
      - name: azure-config-file
        mountPath: /etc/kubernetes
        readOnly: true
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: {{ include "resource.default.name" . }}-external-dns-private
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/managed-by: {{ .Chart.Name }}
spec:
  catalog: default
  name: external-dns-app
  {{- $_ := set $ "appName" "external-dns" }}
  {{- $appVersion := include "cluster.app.version" $ }}
  version: {{ $appVersion }}
  namespace: kube-system
  config:
    configMap:
      name: {{ include "resource.default.name" . }}-cluster-values
      namespace: {{ .Release.Namespace }}
  userConfig:
    configMap:
      name: {{ include "resource.default.name" . }}-external-dns-private-user-values
      namespace: {{ .Release.Namespace }}
  {{- if .Values.global.apps.externalDnsPrivate.extraConfigs }}
  extraConfigs:
  {{- range .Values.global.apps.externalDnsPrivate.extraConfigs }}
  - kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace | default $.Release.Namespace }}
    priority: {{ .priority }}
  {{- end }}
  {{- end }}
  kubeConfig:
    inCluster: false
    secret:
      name: {{ include "resource.default.name" . }}-kubeconfig
      namespace: {{ .Release.Namespace }}
    context:
      name: {{ include "resource.default.name" . }}-admin@{{ include "resource.default.name" . }}
{{- end }}
