{{/* Azure-specific external-dns app for private clusters */}}
{{- if eq .Values.global.connectivity.network.mode "private" }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-external-dns-private
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    {{- if .Values.global.metadata.servicePriority }}
    giantswarm.io/service-priority: {{ .Values.global.metadata.servicePriority }}
    {{- end }}
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false
  releaseName: external-dns-private
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: external-dns-app
      {{- $_ := set $ "appName" "external-dns" }}
      version: {{ include "cluster.app.version" $ }}
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-{{ include "cluster.app.catalog" $ }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-prometheus-operator-crd
      namespace: {{ $.Release.Namespace }}
  interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  {{- $externalDnsPrivateHelmValues := (include "azureExternalDnsPrivateHelmValues" .) | fromYaml -}}
  {{- $customExternalDnsPrivateHelmValues := $.Values.global.apps.externalDnsPrivate.values -}}
  {{- if $customExternalDnsPrivateHelmValues }}
  {{- $externalDnsPrivateHelmValues = merge (deepCopy $customExternalDnsPrivateHelmValues) $externalDnsPrivateHelmValues -}}
  {{- end }}
  {{- if $externalDnsPrivateHelmValues }}
  values: {{- $externalDnsPrivateHelmValues | toYaml | nindent 4 }}
  {{- end }}
  {{- if $.Values.global.apps.externalDnsPrivate.extraConfigs }}
  valuesFrom:
    {{- range $config := $.Values.global.apps.externalDnsPrivate.extraConfigs }}
    - kind: {{ $config.kind }}
      name: {{ $config.name }}
      valuesKey: values
      optional: {{ $config.optional | default false  }}
    {{- end }}
  {{- end }}
{{- end }}
