{{- if semverCompare "<1.25.0" .Capabilities.KubeVersion.Version -}}
---
{{- include "psps" . }}
{{- end }}
---
{{- include "cluster" . }}
---
{{- include "azure-cluster" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-pools" . }}
---
{{- include "machine-deployments" . }}
---
{{- if .Values.bastion.enabled -}}
{{- include "bastion-machine-deployment" . }}
---
{{- end }}
