{{- if semverCompare "<1.25.0" .Values.internal.kubernetesVersion -}}
---
{{- include "psps" . }}
{{- end }}
---
{{- include "azure-cluster" . }}
---
{{- include "containerd-config-secret" . }}
---
{{- include "provider-specific-files" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-deployments" . }}
