{{- if semverCompare "<1.25.0" .Capabilities.KubeVersion.Version -}}
---
{{- include "psps" . }}
{{- end }}
---
{{- include "helmrepository-default" . }}
---
{{- include "cni-driver-helm-release" . }}
---
{{- include "cloud-controller-manager-helm-release" . }}
---
{{- include "cloud-node-manager-helm-release" . }}
---
{{- include "csi-driver-helm-release" . }}
---
{{- include "coredns-helm-release" . }}
---
{{- include "helmreleases-cleanup-hook" . }}
---
{{- include "cluster" . }}
---
{{- include "azure-cluster" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-deployments" . }}
---
{{- if .Values.connectivity.bastion.enabled -}}
{{- include "bastion-machine-deployment" . }}
---
{{- end }}
