{{- include "azure-cluster" . }}
---
{{- include "containerd-config-secret" . }}
---
{{- include "provider-specific-files" . }}
---
{{- include "control-plane" . }}
---
{{- include "machine-deployments" . }}
