name: Schemalint
on:
  pull_request: {}

jobs:
  validate:
    name: Validate values.schema.json
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Install schemalint
        run: |
          go install github.com/giantswarm/schemalint@latest
      - name: Run schemalint
        run: |
          schemalint verify ./helm/cluster-azure/values.schema.json --rule-set cluster-app
